{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kserve-controller.serviceAccountName" . }}
  labels:
    {{- include "kserve-controller.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
{{- if and .Values.serviceAccount.create .Values.serviceAccountRunners.create }}
---
{{- end }}
{{- if .Values.serviceAccountRunners.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kserve-controller.serviceAccountNameRunners" . }}
  labels:
    {{- include "kserve-controller.labels" . | nindent 4 }}
  {{- with .Values.serviceAccountRunners.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccountRunners.automount }}
{{- end }}
